spring.application.name=security
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15})-%msg%n}

spring.security.user.name=suhail
spring.security.user.password=12345